In [3]:
#Import main lib

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn import metrics

In [5]:
#Data Processing and Collection
car_dataset = pd.read_csv('/content/CAR DETAILS FROM CAR DEKHO.csv')
car_dataset.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [6]:
#Checking the number of rows and columns
car_dataset.shape

(4340, 8)

In [7]:
#getting some information about the dataset
car_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [8]:
car_dataset.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')

In [9]:
#Encoding the categorical data


# encoding "Fuel_Type" Column
car_dataset.replace({'Fuel_Type':{'Petrol':0,'Diesel':1,'CNG':2}},inplace=True)

# encoding "Seller_Type" Column
car_dataset.replace({'Seller_Type':{'Dealer':0,'Individual':1}},inplace=True)

# encoding "Transmission" Column
car_dataset.replace({'Transmission':{'Manual':0,'Automatic':1}},inplace=True)

In [10]:
car_dataset.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [12]:
X = car_dataset.drop(['name','selling_price'],axis=1)
Y = car_dataset['selling_price']

In [13]:
print(X)

      year  km_driven    fuel seller_type transmission         owner
0     2007      70000  Petrol  Individual       Manual   First Owner
1     2007      50000  Petrol  Individual       Manual   First Owner
2     2012     100000  Diesel  Individual       Manual   First Owner
3     2017      46000  Petrol  Individual       Manual   First Owner
4     2014     141000  Diesel  Individual       Manual  Second Owner
...    ...        ...     ...         ...          ...           ...
4335  2014      80000  Diesel  Individual       Manual  Second Owner
4336  2014      80000  Diesel  Individual       Manual  Second Owner
4337  2009      83000  Petrol  Individual       Manual  Second Owner
4338  2016      90000  Diesel  Individual       Manual   First Owner
4339  2016      40000  Petrol  Individual       Manual   First Owner

[4340 rows x 6 columns]

In [14]:
print(Y)

0        60000
1       135000
2       600000
3       250000
4       450000
         ...
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, random_state=2)

In [16]:
# loading the linear regression model
lin_reg_model = LinearRegression()

In [20]:
lin_reg_model.fit(X_train,Y_train)

ValueError: could not convert string to float: 'Diesel'

In [19]:
X = pd.get_dummies(X, columns=['fuel'])  # Replace 'Fuel_Type' with the actual column name